### ISSUE TITLE
Fieldset for highlight.js configuration seems to contain all other plugins configuration

### ISSUE THREAD

**Issue by julienw** [franck-paul/hljs#4]
Hi,
I went to the blog configuration (in `/admin/index.php?process=BlogPref`), and then proceeded to the plugins configuration. This looked strange:
![image](https://github.com/franck-paul/hljs/assets/454175/439383e9-460f-4af5-abfc-031daca7d987)

As you see, the fieldset for the highlight.js plugin also containes all other plugins' configuration blocks.

Here is what the HTML in the devtools looks like, in case it helps:
![image](https://github.com/franck-paul/hljs/assets/454175/cf277db2-0588-4f94-9b24-c867b36ba6d4)

I'm not sure where the `<fieldset>` gets defined, also I see some plugins use `<div class="fieldset">` too.

**Comment by franck-paul** [comment]
It's a problem in (dc)Highlight.js I presume, not in hljs (see [https://plugins.dotaddict.org/dc2/details/dcHighlight).](https://plugins.dotaddict.org/dc2/details/dcHighlight).)

I'm not the maintainer of it, sorry.

**Comment by julienw** [comment]
AH indeed. Not sure why I installed that one... Thanks
