### ISSUE TITLE
The JavaScript file for highlight.js isn't loaded

### ISSUE THREAD

**Issue by julienw** [franck-paul/hljs#5]
Hi, it's me again :-)

It looks like the highlight.js file isn't loaded in my installation. As a result there's no syntax highlighting. I also see no error in the Web Console.
Is there anything I'm missing? Something to configure elsewhere?
In case it's useful, I'm using the ductile theme.

Thanks Franck

**Comment by franck-paul** [comment]
Any URL to see it?

**Comment by julienw** [comment]
You can see in https://everlong.org/blog/index.php/post/2015/07/Mes-probl%C3%A8mes-de-suspend
The part that should be syntax highlighted is the block right after `Puis j'ai édité /usr/local/bin/disable-xhc-wakeup avec ce contenu:`.

Thanks again

**Comment by julienw** [comment]
![image](https://github.com/franck-paul/hljs/assets/454175/045be8e7-ccd9-4713-b9a9-e62cc719296d)
^^^ again a user problem...

but I'm surprised that the macros are registered when it's unchecked :-)
(macros from https://github.com/franck-paul/hljs/blob/main/src/CoreBehaviors.php#L23-L39)

**Comment by franck-paul** [comment]
I will verify this issue (registered macro).

My last test:
![screenshot_2024-01-29_11-32-48_AM](https://github.com/franck-paul/hljs/assets/307049/84cfddd7-bca3-45a0-966c-778f0de0937d)

With the following source (wiki syntax):
```
HLJS native:
///hljs bash
#!/bin/sh

if grep -q XHC.*enabled /proc/acpi/wakeup ; then
  echo XHC > /proc/acpi/wakeup
fi
///

YASH compatiblity:
///yash bash
#!/bin/sh

if grep -q XHC.*enabled /proc/acpi/wakeup ; then
  echo XHC > /proc/acpi/wakeup
fi
///

SyntaxeHL compatibility:
///[bash]
#!/bin/sh

if grep -q XHC.*enabled /proc/acpi/wakeup ; then
  echo XHC > /proc/acpi/wakeup
fi
///

Code compatibility:
///code bash
#!/bin/sh

if grep -q XHC.*enabled /proc/acpi/wakeup ; then
  echo XHC > /proc/acpi/wakeup
fi
///
```
